### ISSUE TITLE
Cities: Skylines not launching

### ISSUE THREAD

**Issue by Arken-Lunk** [anticitizn/creamlinux#24] opened 2024-02-09 13:36 UTC
Hi, so I followed the installation steps, chmodded the Cream.sh file, but C:S just doesn't launch. I saw a similar issue in here, and one answer got it working, but setting the exact same launch parameters didn't help...

Info: 
![image](https://github.com/anticitizn/creamlinux/assets/110853531/f9d04130-19a4-434d-a7d3-1823a4d78e4c)

konsole log: 
```
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
./cream.sh: 25: Cities.x64: not found
ERROR: ld.so: object '/home/arken/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

Thanks!

**Comment by anticitizn** [comment] 2024-02-10 13:11
Hi there, it was me that got it to launch. Unfortunately the DLCs still do not work, because Cities Skylines uses a Steam API function to retrieve owned DLCs different from most games that creamlinux hasn't patched. I was trying to get it to work some time ago, but no luck so far. Will update you if there's any progress on this!

**Comment by Arken-Lunk** [comment] 2024-02-10 13:59
Okay, thanks!!

**Comment by anticitizn** [comment] 2024-03-25 09:48
Hi, I'm closing this as a duplicate of #7. If there's any progress in this direction I will post in that issue and tag you there.

**Closed by anticitizn** 2024-03-25 09:48 UTC
